version: '3.7'
services:
  service:
    container_name: stg-moneystats-service
    image: ${DOCKER_REPOSITORY}:${APP_VERSION}
    hostname: stg.moneystats.service
    ports:
      - "8001-8002:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=deploy
      - DATABASE_JDBC_URL=${DATABASE_JDBC_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - GITHUB_AUTH_TOKEN=${GITHUB_AUTH_TOKEN}
      - TOKEN_INVITE=${TOKEN_INVITE}
      - CONTEXT_PATH=${CONTEXT_PATH}
      - SCHEDULER_MARKET_DATA_ACTIVE=${SCHEDULER_ACTIVE}
      - SCHEDULER_FOREX_ACTIVE=${SCHEDULER_ACTIVE}
      - SCHEDULER_MARKET_DATA_QUANTITY=${SCHEDULER_MARKET_DATA_QUANTITY}
      - SCHEDULER_MARKET_DATA_DELAY_START=${SCHEDULER_MARKET_DATA_DELAY_START}
      - SCHEDULER_MARKET_DATA_DELAY_END=${SCHEDULER_MARKET_DATA_DELAY_END}
      - REST_CLIENT_ANY_API_TOKEN=${REST_CLIENT_ANY_API_TOKEN}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - CLIENT_ID_TOKEN=${CLIENT_ID_TOKEN}
      - SCHEDULER_FOREX_DELAY_START=${SCHEDULER_FOREX_DELAY_START}
      - SCHEDULER_FOREX_DELAY_END=${SCHEDULER_FOREX_DELAY_END}
      - GCLOUD_PROJECT=${GCLOUD_PROJECT}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      # Monta il volume "microservice" nella cartella /secrets (in sola lettura)
      - microservice:/secrets:ro
    deploy:
      replicas: 1
    networks:
      docker-network:
        aliases:
          - stg.moneystats.service

networks:
  docker-network:
    external: true

volumes:
  # Il volume "microservice" verr√† creato automaticamente se non esiste
  microservice: