name: Deploy-STG

on:
  push:
    branches: [ develop ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}

jobs:
  checkout-and-setup:
    name: üîß Checkout and Setup
    runs-on: ubuntu-latest
    steps:
      - name: "‚òÅÔ∏è Checkout Repository"
        uses: actions/checkout@v3

      - name: Set up JDK and Maven
        id: setup
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

  install-test-and-build:
    name: üå± Install, üìÇ Test and Build
    runs-on: ubuntu-latest
    needs: checkout-and-setup
    steps:
      - uses: actions/checkout@v3

      - name: ‚¨áÔ∏è Install dependencies
        run: |
          mvn -X clean install

      - name: üìÇ Test with Maven
        run: |
          mvn test

      - name: üìÇ Build with Maven
        run: |
          mvn -B package --file pom.xml -DskipTests

  set-release-version:
    name: üìù Set Release Version
    runs-on: ubuntu-latest
    needs: [ install-test-and-build, checkout-and-setup ]
    steps:
      - name: Set Release version env variable
        run: |
          cd ${{ needs.checkout-and-setup.outputs.setup-info.checkout-path }}
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

  docker-login:
    name: üê≥ Docker Login
    runs-on: ubuntu-latest
    needs: set-release-version
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

  build-and-push-docker:
    name: üöÄ Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: [ set-release-version, docker-login ]
    steps:
      - uses: actions/checkout@v3
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6.2
        with:
          image: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}
          tags: ${{ env.RELEASE_VERSION }}, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          multiPlatform: true
          platform: linux/amd64,linux/arm64
